### ISSUE TITLE
Error: Failed to parse (unnamed) as a valid auto format key: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by lpellegr** [oracle-actions/configure-kubectl-oke#30]
Using `oracle-actions/configure-kubectl-oke@v1.3.2` in a Github Actions Workflow running on Github ubuntu latest:

> Run oracle-actions/configure-kubectl-oke@v1.3.2
> Installing Oracle Cloud Infrastructure CLI
>   /usr/bin/python -m pip install oci-cli
>   Defaulting to user installation because normal site-packages is not writeable
>   Collecting oci-cli
>     Downloading oci_cli-3.37.[11](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:12)-py3-none-any.whl.metadata (6.9 kB)
>   Collecting oci==2.[12](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:13)3.0 (from oci-cli)
>     Downloading oci-2.123.0-py3-none-any.whl.metadata (5.2 kB)
>   Collecting arrow>=1.0.0 (from oci-cli)
>     Downloading arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
>   Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from oci-cli) (2020.6.20)
>   Collecting click==8.0.4 (from oci-cli)
>     Downloading click-8.0.4-py3-none-any.whl.metadata (3.2 kB)
>   Requirement already satisfied: cryptography<43.0.0,>=3.2.1 in /usr/lib/python3/dist-packages (from oci-cli) (3.4.8)
>   Collecting jmespath==0.10.0 (from oci-cli)
>     Downloading jmespath-0.10.0-py2.py3-none-any.whl.metadata (8.0 kB)
>   Collecting python-dateutil<3.0.0,>=2.5.3 (from oci-cli)
>     Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
>   Requirement already satisfied: pytz>=2016.10 in /usr/lib/python3/dist-packages (from oci-cli) (2022.1)
>   Requirement already satisfied: six>=1.15.0 in /usr/lib/python3/dist-packages (from oci-cli) (1.16.0)
>   Collecting terminaltables==3.1.10 (from oci-cli)
>     Downloading terminaltables-3.1.10-py2.py3-none-any.whl.metadata (3.5 kB)
>   Requirement already satisfied: pyOpenSSL<25.0.0,>=17.5.0 in /usr/lib/python3/dist-packages (from oci-cli) (21.0.0)
>   Requirement already satisfied: PyYAML<=6.0.1,>=5.4 in /usr/lib/python3/dist-packages (from oci-cli) (5.4.1)
>   Collecting prompt-toolkit==3.0.29 (from oci-cli)
>     Downloading prompt_toolkit-3.0.29-py3-none-any.whl.metadata (7.1 kB)
>   Collecting circuitbreaker<2.0.0,>=1.3.1 (from oci==2.123.0->oci-cli)
>     Downloading circuitbreaker-1.4.0.tar.gz (9.7 kB)
>     Preparing metadata (setup.py): started
>     Preparing metadata (setup.py): finished with status 'done'
>   Collecting wcwidth (from prompt-toolkit==3.0.29->oci-cli)
>     Downloading wcwidth-0.2.[13](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:14)-py2.py3-none-any.whl.metadata ([14](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:15) kB)
>   Collecting types-python-dateutil>=2.8.10 (from arrow>=1.0.0->oci-cli)
>     Downloading types_python_dateutil-2.8.19.20240106-py3-none-any.whl.metadata (1.8 kB)
>   Downloading oci_cli-3.37.11-py3-none-any.whl (46.8 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 MB 62.9 MB/s eta 0:00:00
>   Downloading click-8.0.4-py3-none-any.whl (97 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 kB 24.3 MB/s eta 0:00:00
>   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
>   Downloading oci-2.123.0-py3-none-any.whl (25.6 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.6/25.6 MB 90.8 MB/s eta 0:00:00
>   Downloading prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.5/381.5 kB 71.8 MB/s eta 0:00:00
>   Downloading terminaltables-3.1.10-py2.py3-none-any.whl ([15](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:16) kB)
>   Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB [19](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:20).6 MB/s eta 0:00:00
>   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 55.3 MB/s eta 0:00:00
>   Downloading types_python_dateutil-2.8.19.[20](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:21)240106-py3-none-any.whl (9.7 kB)
>   Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
>   Building wheels for collected packages: circuitbreaker
>     Building wheel for circuitbreaker (setup.py): started
>     Building wheel for circuitbreaker (setup.py): finished with status 'done'
>     Created wheel for circuitbreaker: filename=circuitbreaker-1.4.0-py3-none-any.whl size=7519 sha256=a19afaa07639c39d5b1d6c4676efa3b85325a4bf7cb2e502b8257fec31de778a
>     Stored in directory: /home/runner/.cache/pip/wheels/3c/be/64/266b6ce2ef1130de5e419f04805acbb2df5a4ab1b91348f25b
>   Successfully built circuitbreaker
>   Installing collected packages: wcwidth, circuitbreaker, types-python-dateutil, terminaltables, python-dateutil, prompt-toolkit, jmespath, click, oci, arrow, oci-cli
>   Successfully installed arrow-1.3.0 circuitbreaker-1.4.0 click-8.0.4 jmespath-0.10.0 oci-2.1[23](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:24).0 oci-cli-3.37.11 prompt-toolkit-3.0.29 python-dateutil-2.9.0.post0 terminaltables-3.1.10 types-python-dateutil-2.8.19.20[24](https://github.com/ipregistry/ipregistry-api/actions/runs/8124397693/job/22205822311#step:4:25)0106 wcwidth-0.2.13
> Error: Failed to parse (unnamed) as a valid auto format key: Attempt to access memory outside buffer bounds

**Comment by Djelibeybi** [comment]
Does this happen consistently or was this a once-off occurrence? Are you able to share the GitHub Actinos workflow?

**Comment by lpellegr** [comment]
The error happens for all runs. I cannot share the full workflow but it basically looks as follows:

```
jobs:
  install-kubectl:
    runs-on: [ ubuntu-latest ]
    name: Install Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.region }}

    steps:
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.clusterId }}

      - name: Run Kubectl get nodes
        run: kubectl get nodes

      - name: Run Kubectl get pods
        run: kubectl get pods

      - name: Run Kubectl rollout restart
        run: kubectl rollout restart deployment
```
